# Generated by Django 5.0.6 on 2024-07-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolment',
        ),
    ]
