# Generated by Django 5.0.6 on 2024-07-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_remove_student_enrolment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolment',
            field=models.ManyToManyField(to='app6.course'),
        ),
    ]
